export const wilayas = [
  { ar: 'أدرار', fr: 'Adrar' },
  { ar: 'الشلف', fr: 'Chlef' },
  { ar: 'الأغواط', fr: 'Laghouat' },
  { ar: 'أم البواقي', fr: 'Oum El Bouaghi' },
  { ar: 'باتنة', fr: 'Batna' },
  { ar: 'بجاية', fr: 'Bejaia' },
  { ar: 'بسكرة', fr: 'Biskra' },
  { ar: 'بشار', fr: 'Bechar' },
  { ar: 'البليدة', fr: 'Blida' },
  { ar: 'البويرة', fr: 'Bouira' },
  { ar: 'تمنراست', fr: 'Tamanrasset' },
  { ar: 'تبسة', fr: 'Tebessa' },
  { ar: 'تلمسان', fr: 'Tlemcen' },
  { ar: 'تيارت', fr: 'Tiaret' },
  { ar: 'تيزي وزو', fr: 'Tizi Ouzou' },
  { ar: 'الجزائر', fr: 'Alger' },
  { ar: 'الجلفة', fr: 'Djelfa' },
  { ar: 'جيجل', fr: 'Jijel' },
  { ar: 'سطيف', fr: 'Setif' },
  { ar: 'سعيدة', fr: 'Saida' },
  { ar: 'سكيكدة', fr: 'Skikda' },
  { ar: 'سيدي بلعباس', fr: 'Sidi Bel Abbes' },
  { ar: 'عنابة', fr: 'Annaba' },
  { ar: 'قالمة', fr: 'Guelma' },
  { ar: 'قسنطينة', fr: 'Constantine' },
  { ar: 'المدية', fr: 'Medea' },
  { ar: 'مستغانم', fr: 'Mostaganem' },
  { ar: 'المسيلة', fr: 'Msila' },
  { ar: 'معسكر', fr: 'Mascara' },
  { ar: 'ورقلة', fr: 'Ouargla' },
  { ar: 'وهران', fr: 'Oran' },
  { ar: 'البيض', fr: 'El Bayadh' },
  { ar: 'إليزي', fr: 'Illizi' },
  { ar: 'برج بوعريريج', fr: 'Bordj Bou Arreridj' },
  { ar: 'بومرداس', fr: 'Boumerdes' },
  { ar: 'الطارف', fr: 'El Tarf' },
  { ar: 'تندوف', fr: 'Tindouf' },
  { ar: 'تيسمسيلت', fr: 'Tissemsilt' },
  { ar: 'الوادي', fr: 'El Oued' },
  { ar: 'خنشلة', fr: 'Khenchela' },
  { ar: 'سوق أهراس', fr: 'Souk Ahras' },
  { ar: 'تيبازة', fr: 'Tipaza' },
  { ar: 'ميلة', fr: 'Mila' },
  { ar: 'عين الدفلى', fr: 'Ain Defla' },
  { ar: 'النعامة', fr: 'Naama' },
  { ar: 'عين تيموشنت', fr: 'Ain Temouchent' },
  { ar: 'غرداية', fr: 'Ghardaia' },
  { ar: 'غليزان', fr: 'Relizane' },
  { ar: 'تيميمون', fr: 'Timimoun' },
  { ar: 'برج باجي مختار', fr: 'Bordj Badji Mokhtar' },
  { ar: 'أولاد جلال', fr: 'Ouled Djellal' },
  { ar: 'بني عباس', fr: 'Beni Abbes' },
  { ar: 'عين صالح', fr: 'In Salah' },
  { ar: 'عين قزام', fr: 'In Guezzam' },
  { ar: 'توقرت', fr: 'Touggourt' },
  { ar: 'جانت', fr: 'Djanet' },
  { ar: 'المغير', fr: 'El Mghair' },
  { ar: 'المنيعة', fr: 'El Meniaa' },
] as const

export function getDeliveryFee(deliveryFees: Record<string, number> | undefined, wilaya: string, fallback = 500) {
  if (!wilaya) return fallback

  const match = wilayas.find((item) => item.ar === wilaya || item.fr === wilaya)
  const key = match?.ar || wilaya

  return deliveryFees?.[key] ?? fallback
}
